#! /bin/bash

# *****************************
#       Version 2.0.11
# *****************************


# Fedora image read url as parameter
FEDORAURL=${1:-"https://download.fedoraproject.org/pub/fedora/linux/releases/32/Workstation/aarch64/images/Fedora-Workstation-32-1.6.aarch64.raw.xz"}
FEDORARAW="$(basename -s .xz "${FEDORAURL}")"

# Set globals
TMPDIR=/var/tmp/fedora-installer
MEDIADIR=/var/tmp/fedora-installer-media
ARCH='aarch64'
CARCH=$(uname -m)
# systemd-nspawn --resolv-conf has been buggy. If you have issues you can try,
# --resolv-conf=auto --resolv-conf=copy-host or --bind-ro=/etc/resolv.conf
# It all depends how resolv.conf is managed on host and in image.
NSPAWN='systemd-nspawn -q --resolv-conf=auto --timezone=off -D'
LOOP=$(losetup -f)

# set colorscheme
export DIALOGRC="./dialogrc_gui"

# clearing variables
DEVICE="Pinebook Pro"
EDITION="Fedora Workstation"
USER=""
USERGROUPS=""
FULLNAME=""
PASSWORD=""
CONFIRMPASSWORD=""
CONFIRMROOTPASSWORD=""
ROOTPASSWORD=""
SDCARD=""
SDTYP=""
SDDEV=""
DEV_NAME=""
TIMEZONE=""
LOCALE=""
HOSTNAME=""

# check if root
if [ "$EUID" -ne 0 ]; then
    echo "*******************************************************************************************"
    echo "*                                                                                         *"
    echo "*     This script requires root permissions to run. Please run as root or with sudo!      *"
    echo "*                                                                                         *"
    echo "*******************************************************************************************"
  exit
fi

# Sanity checks for dependencies
declare -a DEPENDNECIES=("sed" "rsync" "systemd-nspawn" "wget" "dialog" "bsdtar" "openssl" "awk" )

for i in "${DEPENDNECIES[@]}"; do
  if ! [[ -f "/bin/$i" || -f "/sbin/$i" || -f "/usr/bin/$i" || -f "/usr/sbin/$i" ]] ; then
    echo "$i command is missing! Please install the relevant package."
    exit 1
  fi
done

if [[ "$CARCH" != "aarch64" ]]; then
if ! [[ -f "/usr/lib/binfmt.d/qemu-aarch64-static.conf" || -f "/usr/lib/binfmt.d/qemu-static.conf" ]]; then
    echo "qemu-aarch64-static.conf file is missing. Please install the relevant package."
    exit 1
fi
fi


# Functions
msg() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    GREEN="${BOLD}\e[1;32m"
      local mesg=$1; shift
      printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
 }

info() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    BLUE="${BOLD}\e[1;34m"
      local mesg=$1; shift
      printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
 }

usage_build_installer() {
    echo "Usage: ${0##*/} [options]"
    echo '    -h                 This help'
    echo ''
    echo ''
    exit $1
}

get_timer(){
    echo $(date +%s)
}

# $1: start timer
elapsed_time(){
    echo $(echo $1 $(get_timer) | awk '{ printf "%0.2f",($2-$1)/60 }')
}

show_elapsed_time(){
    msg "Time %s: %s minutes..." "$1" "$(elapsed_time $2)"
}

prepare_media() {
    msg "Prepare source media..."

    # fetch and extract fedora image
    if [ ! -f "$MEDIADIR/$FEDORARAW" ]; then
      info "Downloading Fedora Image..."
      wget -q --show-progress --progress=bar:force:noscroll $FEDORAURL --output-document $MEDIADIR/$FEDORARAW.xz
      info "Decompress Fedora Image..."
      xz --decompress $MEDIADIR/$FEDORARAW.xz
    fi
}

install_fedora() {
    msg "Install Fedora from media..."
	
    info "Making mount directories..."
    mkdir -p $TMPDIR/imgfs/{2,3}

    info "Mounting Fedora image..."

    losetup $LOOP $MEDIADIR/$FEDORARAW
    partprobe -s $LOOP
    mount "$LOOP"p2 $TMPDIR/imgfs/2
    mount "$LOOP"p3 $TMPDIR/imgfs/3

    info "Copying Fedora files (progress status sucks)..."
    rsync -a --info=progress2 $TMPDIR/imgfs/3/* $TMPDIR/root/
    rsync -a --info=progress2 $TMPDIR/imgfs/2/* $TMPDIR/root/boot/

    info "Unmounting Fedora media..."
    umount "$LOOP"p2
    umount "$LOOP"p3
    losetup -d $LOOP

    info "Deleting temp directories..."
    rmdir $TMPDIR/imgfs/2
    rmdir $TMPDIR/imgfs/3
    rmdir $TMPDIR/imgfs

}

upgrade_fedora() {
    msg "Upgrade Fedora and add packages..."

    info "Remove uneeded packages..."
    $NSPAWN $TMPDIR/root dnf remove -y kernel kernel-core kernel-modules grub2-common grub2-efi-aa64 grub2-tools grub2-tools-extra grub2-tools-minimal grubby bcm283x-firmware shim-aa64 --noautoremove 1> /dev/null 2>&1
    info "Clean /boot..."
    rm -rf $TMPDIR/root/boot/*
    info "Upgrade Fedora..."
    mkdir -p $TMPDIR/dnf
    mount -o bind $TMPDIR/dnf $TMPDIR/root/var/cache/dnf
    $NSPAWN $TMPDIR/root dnf upgrade -y --refresh

    info "Enable copr/aptupdate/pinebook-pro..."
    $NSPAWN $TMPDIR/root dnf copr enable -y aptupdate/pinebook-pro
    $NSPAWN $TMPDIR/root dnf makecache

    info "Install extra packages..."
    $NSPAWN $TMPDIR/root dnf install -y acpid
    
    info "Install Pinebook Pro packages..."
    $NSPAWN $TMPDIR/root dnf install -y kernel-pbp uboot-pinebookpro ap6256-firmware pbp-keyboard-hwdb pinebookpro-suspend pinebookpro-audio
    
    info "Enable services from packages..."
    $NSPAWN $TMPDIR/root systemctl enable acpid.service

    info "Clear dnf cache..."
    umount $TMPDIR/root/var/cache/dnf 
    $NSPAWN $TMPDIR/root dnf clean all 1> /dev/null 2>&1
    
}
	
configure_fedora() {
    msg "Configure Fedora..."
    info "Run SELinux autorelabel all files first boot..."
    touch $TMPDIR/root/.autorelabel

    info "Update extlinux.conf with UUID..."
    # Get UUID
    BOOTUUID=$(blkid -s UUID -o value "${SDCARD}${SDDEV}1")
    ROOTUUID=$(blkid -s UUID -o value "${SDCARD}${SDDEV}2")
    
    # Configure extlinux.conf
    mkdir ${TMPDIR}/root/boot/extlinux/ -p
    echo "LABEL Fedora PinebookPro" > ${TMPDIR}/root/boot/extlinux/extlinux.conf 
    echo "KERNEL /Image" >> ${TMPDIR}/root/boot/extlinux/extlinux.conf 
    echo "FDT /dtbs/rockchip/rk3399-pinebook-pro.dtb" >> ${TMPDIR}/root/boot/extlinux/extlinux.conf 
    echo "INITRD /initramfs-linux.img" >> ${TMPDIR}/root/boot/extlinux/extlinux.conf 
    echo "APPEND console=tty1 console=ttyS2,1500000 root=UUID=${ROOTUUID} rw rhgb quiet" >> ${TMPDIR}/root/boot/extlinux/extlinux.conf

    info "Update fstab with UUID..."
    # Edit fstab
    echo "UUID=${ROOTUUID}  /   ext4    defaults        0       1"  > $TMPDIR/root/etc/fstab
    echo "UUID=${BOOTUUID}  /boot   ext4    defaults        0       2" >> $TMPDIR/root/etc/fstab

    info "Set timezone..."
    $NSPAWN $TMPDIR/root ln -sf /usr/share/zoneinfo/"$TIMEZONE" /etc/localtime 1> /dev/null 2>&1
    
    info "Set locale..."
    echo "LANG=$LOCALE" | tee --append $TMPDIR/root/etc/locale.conf 1> /dev/null 2>&1
    
    info "Set keymap..."
    echo "KEYMAP=$CLIKEYMAP" | tee --append $TMPDIR/root/etc/vconsole.conf 1> /dev/null 2>&1
    echo 'Section "InputClass"' > $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    echo 'Identifier "system-keyboard"' >> $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    echo 'Option "XkbLayout" "us"' >> $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    echo 'EndSection' >> $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    sed -i s/"us"/"$X11KEYMAP"/ $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf

    info "Set hostname..."
    echo "$HOSTNAME" > $TMPDIR/root/etc/hostname

    info "Fix update-uboot for pinebook-pro-rk3399"
    ln -s ../socs.d/Rockchips-ARMv8 $TMPDIR/root/usr/share/arm-image-installer/boards.d/pinebook-pro-rk3399

    info "Setting up users..."
    #setup users
    echo "$USER" > $TMPDIR/user
    echo "$PASSWORD" > $TMPDIR/password
    echo "$ROOTPASSWORD" > $TMPDIR/rootpassword

    info "Setting password for root ..."
    $NSPAWN $TMPDIR/root awk -i inplace -F: "BEGIN {OFS=FS;} \$1 == \"root\" {\$2=\"$(openssl passwd -1 $(cat $TMPDIR/rootpassword))\"} 1" /etc/shadow 1> /dev/null 2>&1

    info "Adding user..."
    $NSPAWN $TMPDIR/root useradd -m -G wheel -p $(openssl passwd -1 $(cat $TMPDIR/password)) -s /bin/bash $(cat $TMPDIR/user) 1> /dev/null 2>&1
    $NSPAWN $TMPDIR/root usermod -aG $USERGROUPS $(cat $TMPDIR/user) 1> /dev/null 2>&1
    $NSPAWN $TMPDIR/root chfn -f "$FULLNAME" $(cat $TMPDIR/user) 1> /dev/null 2>&1
	
    # Remove temp files on host
    rm -rf $TMPDIR/user $TMPDIR/password $TMPDIR/rootpassword

    msg "$DEVICE $EDITION install complete"
}

prepare_card () {
    msg "Getting $SDCARD ready for $DEVICE..."
    # umount and clear SD card
    umount ${SDCARD}$* 1> /dev/null 2>&1
    umount ${SDCARD}$* 1> /dev/null 2>&1
    umount ${SDCARD}$* 1> /dev/null 2>&1
    wipefs -a ${SDCARD} 1> /dev/null 2>&1
    echo -e "label:gpt" | sfdisk ${SDCARD} 1> /dev/null 2>&1

    info "Create partitions..."
    #Clear first 32mb
    dd if=/dev/zero of=${SDCARD} bs=1M count=32 1> /dev/null 2>&1

    info "Partition $DEV_NAME"
    info "Partition with efi, boot and root"
    echo -e "label:gpt\nunit:sectors\nfirst-lba:32768" | sfdisk ${SDCARD} 1> /dev/null 2>&1
    echo -e "n\n1\n32768\n+1G\nn\n2\n\n\nx\nA\n1\nr\nw" | fdisk ${SDCARD} 1> /dev/null 2>&1

    info "List partitions..."
    partprobe -s ${SDCARD}
    fdisk -l ${SDCARD}
}

format_card () {
    info "Format partitions on $DEV_NAME"
        mkfs.ext4 -F -O ^metadata_csum,^64bit "${SDCARD}${SDDEV}1" -L "${DEV_NAME}-BOOT" 1> /dev/null 2>&1
        mkfs.ext4 -F -O ^metadata_csum,^64bit "${SDCARD}${SDDEV}2" -L "${DEV_NAME}-ROOT" 1> /dev/null 2>&1
	sleep 1
        mkdir -p $TMPDIR/root
        mount ${SDCARD}${SDDEV}2 $TMPDIR/root
        sleep 1
        mkdir -p $TMPDIR/root/boot
        mount ${SDCARD}${SDDEV}1 $TMPDIR/root/boot
        sleep 1
}

cleanup () {
    msg "Writing bootloader and cleaning up after install..."
    # Flash bootloader
    dd if=$TMPDIR/root/boot/idbloader.img of=${SDCARD} seek=64 conv=notrunc,fsync 1> /dev/null 2>&1
    dd if=$TMPDIR/root/boot/u-boot.itb of=${SDCARD} seek=16384 conv=notrunc,fsync 1> /dev/null 2>&1
    	
    #clean up
    umount $TMPDIR/root/boot
    umount $TMPDIR/root
    partprobe $SDCARD 1> /dev/null 2>&1

    rm -rf $TMPDIR
    msg "Not removing installation media $MEDIADIR"
}

if [ ! -z "$EDITION" ]; then
	USER=$(dialog --clear --title "Fedora ARM Installer" \
	--inputbox "Enter the username you want:
(usernames most be all lowercase)" 8 50 \
	3>&1 1>&2 2>&3 3>&-)
    if [[ "$USER" =~ [A-Z] ]] || [[ "$USER" == *['!'@#\$%^\&*()_+]* ]]; then
    clear
    msg "Configuration aborted! Username contained invalid characters."
    exit 1
    fi
else 
	clear
	exit 1
fi

if [ ! -z "$USER" ]
then
FULLNAME=$(dialog --clear --title "Fedora ARM Installer" \
    --inputbox "Enter desired Full Name for $USER:" 8 50 \
        3>&1 1>&2 2>&3 3>&- \
	)
else
    clear
    exit 1
fi

if [ ! -z "$FULLNAME" ]; then
	PASSWORD=$(dialog --clear --title "Fedora ARM Installer" \
	--insecure --passwordbox "Enter new Password for $USER:" 8 50 \
	3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	exit 1
fi

if [ ! -z "$PASSWORD" ]; then
	CONFIRMPASSWORD=$(dialog --clear --title "Fedora ARM Installer" \
	--insecure --passwordbox "Confirm new Password for $USER:" 8 50 \
	3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	exit 1
fi

if [[ "$PASSWORD" != "$CONFIRMPASSWORD" ]]; then
	clear
	msg "User passwords do not match! Please restart the installer and try again."
	exit 1
fi

if [ ! -z "$CONFIRMPASSWORD" ]; then
	ROOTPASSWORD=$(dialog --clear --title "Fedora ARM Installer" \
	--insecure --passwordbox "Enter new Root Password:" 8 50 \
	3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	exit 1
fi

if [ ! -z "$ROOTPASSWORD" ]; then
	CONFIRMROOTPASSWORD=$(dialog --clear --title "Fedora ARM Installer" \
	--insecure --passwordbox "Confirm new Root Password:" 8 50 \
	3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	exit 1
fi

if [[ "$ROOTPASSWORD" != "$CONFIRMROOTPASSWORD" ]]; then
	clear
	msg "Root passwords do not match! Please restart the installer and try again."
	exit 1
fi

if [ ! -z "$CONFIRMROOTPASSWORD" ]
then

# simple command to put the results of lsblk (just the names of the devices) into an array and make that array populate the options	
	let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( lsblk -dn -o NAME )
	SDCARD=$(dialog --title "Fedora ARM Installer" \
	--menu "Choose your SDCard/eMMC/USB - Be sure the correct drive is selected! 
WARNING! This WILL destroy the data on it!" 20 50 10 \
	"${W[@]}" 3>&2 2>&1 1>&3)

# add /dev/ to the selected option above
	DEV_NAME=$SDCARD
	SDCARD=/dev/$SDCARD
	SDTYP=${SDCARD:5:2}
else 
	clear
	exit 1
fi

if [[ "$SDTYP" = "sd" || "$SDTYP" = "vd" ]]; then
	SDDEV=""
elif [[ "$SDTYP" = "mm" || "$SDTYP" = "lo" || "$SDTYP" = "nv" ]]; then
	SDDEV="p"
else
  clear
  exit 1
fi


if [ ! -z "$SDCARD" ]; then
	let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( timedatectl list-timezones )
	TIMEZONE=$(dialog --clear --title "Fedora ARM Installer" \
	--menu "Choose your timezone!" 20 50 15 \
	"${W[@]}" 3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	exit 1
fi


if [ ! -z "$TIMEZONE" ]; then
	let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( localectl list-locales )
	LOCALE=$(dialog --clear --title "Fedora ARM Installer" \
		--menu "Choose your locale!" 20 50 15 \
		"${W[@]}" 3>&1 1>&2 2>&3 3>&- \
		)
else 
	clear
	exit 1
fi

if [ ! -z "$LOCALE" ]; then
	let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( localectl list-keymaps )
	CLIKEYMAP=$(dialog --clear --title "Fedora ARM Installer" \
		--menu "Choose your TTY keyboard layout:" 20 50 15 \
		"${W[@]}" 3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	exit 1
fi

if [ ! -z "$CLIKEYMAP" ]; then
	let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( localectl list-x11-keymap-layouts )
	X11KEYMAP=$(dialog --clear --title "Manjaro ARM Installer" \
		--menu "Choose your X11 keyboard layout:" 20 50 15 \
		"${W[@]}" 3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	exit 1
fi

if [ ! -z "$CLIKEYMAP" ]; then
	HOSTNAME=$(dialog --clear --title "Fedora ARM Installer" \
	--inputbox "Enter desired hostname (fqdn) for this system:" 8 50 \
	3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	exit 1
fi

if [ ! -z "$HOSTNAME" ]; then
	dialog --clear --title "Fedora ARM Installer" \
    --yesno "Is the below information correct:
    Device = $DEVICE
    Edition = $EDITION
    Username = $USER
    Additional usergroups = $USERGROUPS
    Password for $USER = (password hidden)
    Password for root = (password hidden)
    SDCard/eMMC/USB = $SDCARD
    Timezone = $TIMEZONE
    Locale = $LOCALE
    Keyboard layout = $CLIKEYMAP
    Hostname = $HOSTNAME" 20 70 \
    3>&1 1>&2 2>&3 3>&-
else
	clear
	exit 1
fi

response=$?
case $response in
   0) clear; msg "Installation started....";;
   1) clear; msg "Installation aborted...."; exit 1;;
   255) clear; msg "Installation aborted..."; exit 1;;
esac

if [ ! -f "$TMPDIR" ]; then
  rm -rf $TMPDIR
fi

mkdir -p $MEDIADIR
mkdir -p $TMPDIR

# Commands
timer_start=$(get_timer)

prepare_media
prepare_card
format_card
install_fedora
upgrade_fedora
configure_fedora
cleanup
show_elapsed_time "${FUNCNAME}" "${timer_start}"
sync
